### ISSUE TITLE
tried a go get, got an error, not sure what to do

### ISSUE THREAD

**Issue by mcoolin** [devfacet/worker#1]
go get https://github.com/devfacet/worker
package https:/github.com/devfacet/worker: https:/github.com/devfacet/worker: invalid import path: malformed import path "https:/github.com/devfacet/worker": invalid char ':'

**Comment by devfacet** [comment]
What are you trying to do?

Try the following command:
```
go get github.com/devfacet/worker
```

**Comment by mcoolin** [comment]
That worked fine. Thanks

**Comment by mcoolin** [comment]
I am fairly new to go. I have run your test files. I am reviewing your code but I wish you provided a clear description on how to use your library. I am trying to pull it out of the testing files is very time consuming.

**Comment by devfacet** [comment]
There are so many different ways to use this library. I just added an example application https://github.com/devfacet/worker/blob/main/examples/pool/main.go

**Comment by mcoolin** [comment]
Thanks very much for that.
